version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2_network
    volumes:
      - gis_2_static:/data/static/
      - gis_2_media:/data/media/
      - /home/kms01041202735/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80

  django:
    image: gis_2_django:5
    networks:
      - gis_2_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - gis_2_static:/home/gis_1ban_2/staticfiles/
      - gis_2_media:/home/gis_1ban_2/media/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_2_network
    volumes:
      - gis_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: gyul
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  gis_2_network:

volumes:
  gis_2_static:
  gis_2_media:
  gis_mariadb:

secrets:
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  DJANGO_SECRET_KEY:
    external: true